/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Task = IDL.Record({ 'done' : IDL.Bool, 'description' : IDL.Text });
export const CheckedItems = IDL.Record({
  'nETPrep' : IDL.Vec(IDL.Text),
  'students' : IDL.Vec(IDL.Text),
  'riyalah' : IDL.Vec(IDL.Text),
  'certificates' : IDL.Vec(IDL.Text),
  'mABooks' : IDL.Vec(IDL.Text),
});
export const UserData = IDL.Record({
  'dailyTasks' : IDL.Vec(Task),
  'checkedItems' : CheckedItems,
  'monthlyIncome' : IDL.Nat,
});

export const idlService = IDL.Service({
  'isUserDataPersisted' : IDL.Func([], [IDL.Bool], ['query']),
  'loadUserData' : IDL.Func([], [UserData], ['query']),
  'saveUserData' : IDL.Func([CheckedItems, IDL.Nat, IDL.Vec(Task)], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Task = IDL.Record({ 'done' : IDL.Bool, 'description' : IDL.Text });
  const CheckedItems = IDL.Record({
    'nETPrep' : IDL.Vec(IDL.Text),
    'students' : IDL.Vec(IDL.Text),
    'riyalah' : IDL.Vec(IDL.Text),
    'certificates' : IDL.Vec(IDL.Text),
    'mABooks' : IDL.Vec(IDL.Text),
  });
  const UserData = IDL.Record({
    'dailyTasks' : IDL.Vec(Task),
    'checkedItems' : CheckedItems,
    'monthlyIncome' : IDL.Nat,
  });
  
  return IDL.Service({
    'isUserDataPersisted' : IDL.Func([], [IDL.Bool], ['query']),
    'loadUserData' : IDL.Func([], [UserData], ['query']),
    'saveUserData' : IDL.Func([CheckedItems, IDL.Nat, IDL.Vec(Task)], [], []),
  });
};

export const init = ({ IDL }) => { return []; };