/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CheckedItems {
  'nETPrep' : Array<string>,
  'students' : Array<string>,
  'riyalah' : Array<string>,
  'certificates' : Array<string>,
  'mABooks' : Array<string>,
}
export interface Task { 'done' : boolean, 'description' : string }
export interface UserData {
  'dailyTasks' : Array<Task>,
  'checkedItems' : CheckedItems,
  'monthlyIncome' : bigint,
}
export interface _SERVICE {
  'isUserDataPersisted' : ActorMethod<[], boolean>,
  'loadUserData' : ActorMethod<[], UserData>,
  'saveUserData' : ActorMethod<[CheckedItems, bigint, Array<Task>], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];